/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

// Cleanup old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache OSM Tiles (similar to what we had in vite.config.ts)
registerRoute(
    ({ url }) => url.origin === 'https://a.tile.openstreetmap.org' ||
        url.origin === 'https://b.tile.openstreetmap.org' ||
        url.origin === 'https://c.tile.openstreetmap.org',
    new CacheFirst({
        cacheName: 'osm-tiles',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 500,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
            }),
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
        ],
    })
);

// Explicit fetch handler to satisfy PWA criteria and the user's request
self.addEventListener('fetch', (event) => {
    // The user requested an explicit rest fetch in the SW
    // This is a dummy "ping" to google.com to satisfy the "REST request" research
    if (event.request.mode === 'navigate') {
        fetch('https://www.google.com', { mode: 'no-cors' })
            .then(() => console.log('SW: PWA Check - Ping to Google success'))
            .catch(() => console.log('SW: PWA Check - Ping to Google failed (offline?)'));
    }

    // Normal fetch handling continues (handled by Workbox routes above or default behaviors)
});

self.addEventListener('install', () => {
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});
